import './globals.css'
import { NextSeo } from 'next-seo';
import Head from 'next/head'
import { NEXT_SEO_DEFAULT } from '../../next-seo-config';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <NextSeo
          useAppDir={true}
          {...NEXT_SEO_DEFAULT}
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
